CREATE TABLE IF NOT EXISTS address(
    PK_id VARCHAR(100) NOT NULL,
    FK_user_id VARCHAR(100) NOT NULL,
    city VARCHAR(50) NOT NULL,
    state VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,
    street VARCHAR(100) NOT NULL,
    complement VARCHAR(200),
    is_main BOOLEAN DEFAULT(FALSE),


    PRIMARY KEY(PK_id)

);